	// ros::Rate loop(0.5);
	// rotate(degrees2radians(30), degrees2radians(97), false);
	// loop.sleep();
	// move(1,2,true);
	// loop.sleep();
	// rotate(degrees2radians(30), degrees2radians(142), true);
	// loop.sleep();
	// move(1,2.5,true);
	// loop.sleep();
	// rotate(degrees2radians(30), degrees2radians(142), false);
	// loop.sleep();
	// move(1,2,true);
	// loop.sleep();
	// rotate(degrees2radians(30), degrees2radians(90), false);
	// loop.sleep();
	// move(1,1.45,true);
	// loop.sleep();
	// rotate(degrees2radians(30), degrees2radians(120), true);
	// loop.sleep();
	// move(1,1.4,true);
	// loop.sleep();
	// rotate(degrees2radians(30), degrees2radians(120), true);
	// loop.sleep();
	// move(1,1.4,true);
	// loop.sleep();
	// rotate(degrees2radians(30), degrees2radians(64), true);
	// loop.sleep();
	// move(1,2.5,true);
	// loop.sleep();
	// rotate(degrees2radians(30), degrees2radians(123), false);
	// loop.sleep();
	// move(1,1.45,true);
	// loop.sleep();